[package]
name = "tasty_fresh"
version = "0.2.0"
authors = ["Robert Borghese"]
edition = "2018"

[profile.release]
opt-level = 3

[dependencies]
lazy_static = "1.4"
regex = "1"
colored = "1.9"
serde_json = "1.0"
num = "0.2"
glob = "0.3"
path-slash = "0.1"
either = "1.5.3"
